# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Create an ECS Fargate cluster to host the private PyPi mirror

Outputs:
  PyPIMirrorEndpointServiceName:
    Description: The service name of PyPI mirror to use in a VPC Endpoint 
    Value: ''
    Export:
      Name: 'ds-pypimirror-shared-service-endpoint-name'

Parameters:
  StackSetName:
    Type: String 
    Description: A parent stack name 

Conditions:
  FalseCondition: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: FalseCondition
