# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Create the shared VPC and related network resources

Parameters:
  StackSetName:
    Type: String 
    Description: A parent stack name

Conditions:
  FalseCondition: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: FalseCondition