AWSTemplateFormatVersion: 2010-09-09
Description: |
  Create an ECS Fargate cluster to host the private PyPi mirror

Outputs:
  PyPIMirrorEndpointServiceName:
    Description: The service name of PyPI mirror to use in a VPC Endpoint 
    Value: ''
    Export:
      Name: !Sub 'ds-pypimirror-shared-service-endpoint-name'

Parameters:
  StackSetName:
    Type: String 
    Description: A name to be used across all nested stacks 

Conditions:
  FalseCondition: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: FalseCondition
