AWSTemplateFormatVersion: 2010-09-09
Description: |
  MLOps SageMaker Project for multi-account ML model deployment. 
  This template creates a CI/CD pipeline to deploy a given inference image and pretrained Model to two separate account -- staging and production.

Parameters:
  SageMakerProjectName:
    Type: String
    Description: Name of the project
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-zA-Z](-*[a-zA-Z0-9])*

  SageMakerProjectId:
    Type: String
    Description: Service generated Id of the project.

  SeedCodeS3BucketName:
    Type: String
    Description: S3 bucket name where the seed code for MLOps projects for CodeCommit repository is stored

Resources:

  ModelDeployCodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      # Max allowed length: 100 chars
      RepositoryName: !Sub sagemaker-${SageMakerProjectName}-${SageMakerProjectId}-model-deploy # max: 10+33+15+12=70
      RepositoryDescription: !Sub SageMaker Endpoint deployment infrastructure as code for the project ${SageMakerProjectName}
      Code:
        S3:
          Bucket: !Ref SeedCodeS3BucketName 
          Key: sagemaker-mlops/seed-code/mlops-model-deploy-v1.0.zip
        BranchName: main