version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install python3-pip zip -y
      - pip3 install -U pip
      - pip3 install awscli

  build:
    commands:
      - env
      - echo Packaging Cloudformation and uploading to S3...
      - ./make package CFN_BUCKET_NAME=$S3_BUCKET_NAME