version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8

  build:
    commands:
      - env
      - echo Packaging Cloudformation and uploading to S3...
      - make package CFN_BUCKET_NAME=$S3_BUCKET_NAME