version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade --force-reinstall botocore boto3 awscli

  build:
    commands:
      # Create the Model Registry if needed. This code will run when the repo is created
      - python setup.py --sagemaker-project-id "$SAGEMAKER_PROJECT_ID" --sagemaker-project-name "$SAGEMAKER_PROJECT_NAME" --organizational-unit-staging-id "$ORGANIZATIONAL_UNIT_STAGING_ID" --organizational-unit-prod-id "$ORGANIZATIONAL_UNIT_PROD_ID"

      # Export the staging and production configuration files
      - python build.py --model-execution-role "$MODEL_EXECUTION_ROLE_ARN" --model-package-group-name "$SOURCE_MODEL_PACKAGE_GROUP_NAME" --sagemaker-project-id "$SAGEMAKER_PROJECT_ID" --sagemaker-project-name "$SAGEMAKER_PROJECT_NAME" --export-staging-config "$EXPORT_TEMPLATE_STAGING_CONFIG" --export-prod-config "$EXPORT_TEMPLATE_PROD_CONFIG" --sagemaker-execution-role-staging-name "$SAGEMAKER_EXECUTION_ROLE_STAGING_NAME" --sagemaker-execution-role-prod-name "$SAGEMAKER_EXECUTION_ROLE_PROD_NAME"

      # This is a workaround to allow the target accounts to get a file created by SageMaker in the master account
      - python fix_model_permission.py --prod-config-file "$EXPORT_TEMPLATE_PROD_CONFIG"

      # Package the infrastucture as code defined in endpoint-config-template.yml by using AWS CloudFormation.
      # Note that the Environment Variables like ARTIFACT_BUCKET, SAGEMAKER_PROJECT_NAME etc,. used below are expected to be setup by the
      # CodeBuild resrouce in the infra pipeline (in the ServiceCatalog product)
      - aws cloudformation package --template endpoint-config-template.yml --s3-bucket $ARTIFACT_BUCKET --output-template $EXPORT_TEMPLATE_NAME

      # Print the files to verify contents
      - cat $EXPORT_TEMPLATE_STAGING_CONFIG
      - cat $EXPORT_TEMPLATE_PROD_CONFIG

artifacts:
  files:
    - $EXPORT_TEMPLATE_NAME
    - $EXPORT_TEMPLATE_STAGING_CONFIG
    - $EXPORT_TEMPLATE_PROD_CONFIG
