version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade --force-reinstall botocore boto3 awscli

  build:
    commands:
      # Create the Model Registry if needed. This code will run when the CodePipeline is provisioned first time on the creation of SageMake project
      - python setup.py --sagemaker-project-id "$SAGEMAKER_PROJECT_ID" --sagemaker-project-name "$SAGEMAKER_PROJECT_NAME" --model-package-group-name "$SOURCE_MODEL_PACKAGE_GROUP_NAME" --organizational-unit-staging-id "$ORGANIZATIONAL_UNIT_STAGING_ID" --organizational-unit-prod-id "$ORGANIZATIONAL_UNIT_PROD_ID" --env-name "$ENV_NAME" --env-type "$ENV_TYPE"

      # Export the staging and production configuration files
      - python build.py --sagemaker-project-id "$SAGEMAKER_PROJECT_ID" --sagemaker-project-name "$SAGEMAKER_PROJECT_NAME" --model-package-group-name "$SOURCE_MODEL_PACKAGE_GROUP_NAME" --staging-config-name "$STAGING_CONFIG_NAME" --prod-config-name "$PROD_CONFIG_NAME" --sagemaker-execution-role-staging-name "$SAGEMAKER_EXECUTION_ROLE_STAGING_NAME" --sagemaker-execution-role-prod-name "$SAGEMAKER_EXECUTION_ROLE_PROD_NAME" --env-name "$ENV_NAME"

      # This is a workaround to allow the target accounts to get a file created by SageMaker in the master account
      # - python fix_model_permission.py --prod-config-file "$PROD_CONFIG_NAME"

      # Package the infrastucture as code defined in endpoint-config-template.yml by using AWS CloudFormation.
      # Note that the Environment Variables like ARTIFACT_BUCKET, SAGEMAKER_PROJECT_NAME etc,. used below are expected to be setup by the
      # CodeBuild resrouce in the infra pipeline (in the ServiceCatalog product)
      - aws cloudformation package --template ${CFN_TEMPLATE_NAME}.yaml --s3-bucket $ARTIFACT_BUCKET --output-template ${CFN_TEMPLATE_NAME}.yaml

      # Print the files to verify contents
      - cat ${STAGING_CONFIG_NAME}.json
      - cat ${PROD_CONFIG_NAME}.json

artifacts:
  files:
    - ${CFN_TEMPLATE_NAME}.yaml
    - ${STAGING_CONFIG_NAME}.json
    - ${PROD_CONFIG_NAME}.json
